# Densidad de negocios en la CDMX
Quiero ver cómo se ve la densidad de negocios en la cdmx

In [4]:
import os
import sys
sys.path.insert(1, '../')

import math
import json
import time
import requests
import h3pandas
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import geopandas as gpd
from pathlib import Path
from datetime import datetime
import matplotlib.pyplot as plt
from grid_builder import GridBuilder
from mpl_toolkits.axes_grid1 import make_axes_locatable
from google_places_aggregate import GooglePlacesAggregate, PLACE_TYPES_BY_CATEGORY
from shapely.geometry import LineString, MultiLineString, Polygon


warnings.filterwarnings("ignore")
PATH_DATA = '../../data/'
CRS = 4326

In [2]:
def append_items_to_file(path:str, new_data:dict):
    path_parts = path.split("/")
    directory = "/".join(path_parts[:-1])
    filename = path_parts[-1]
    
    Path(directory).mkdir(parents=True, exist_ok=True)
    
    # si el archivo ya existe, lo leemos y tenemos la data actual
    current_data = {}
    if os.path.exists(path):
        with open(path, "r") as f:
            current_data = json.loads(f.read())
        
    # Agregamos los datos
    for key, value in new_data.items():
        current_data[key] = value
        
    # Y guradamos el archivo de nuevo
    with open(path, "w") as json_file:
        json.dump(current_data, json_file, indent=4)
            
    return current_data

In [3]:
# ahora quiero encontrar la densidad de negocios en cada uno de los cells
GOOGLE_API_KEY = "AIzaSyDK7B0Ah4_TreiUT1byTjWrSUHGXYEwfU0"
gpa = GooglePlacesAggregate(api_key=GOOGLE_API_KEY)

In [4]:
vialidades = (
    gpd
    .read_file(os.path.join(PATH_DATA, 'vialidades.json'))
    .assign(
        tipo_vialidad=lambda x: x.TIPO_VIA.map({
            "Vía primaria":"primaria", 
            'Vía de acceso controlado':'acceso_controlado'
        }),
        carriles=lambda x: pd.to_numeric(x.CARRILES, errors='raise'),
        sentidos=lambda x: x.CIRCULA.map({
            "Un sentido":1, 
            "Dos sentidos":2, 
            "Un sentido con carril de contraflujo":2
        })
    )
    .rename({
        'NIVEL':'nivel', 
        'NOMENCLAT':'calle', 
        'NOMBRE':'vialidad', 
        'ID_VIA':'id_via'
    }, axis=1)
    [[
        'id_via', 'vialidad', 'calle', 'tipo_vialidad', 
        'carriles', 'sentidos', 'nivel', 'geometry'
    ]]
    .to_crs(CRS)
)

In [6]:
accidents = (
    pd
    .read_parquet(os.path.join(PATH_DATA, "classified-incidents.parquet"))
    .pipe(lambda df: (
        gpd
        .GeoDataFrame(
            data=df.drop(columns=['latitude', 'longitude']),
            geometry=gpd.points_from_xy(df.longitude, df.latitude),
            crs="EPSG:4326"
        ) 
    ))
)

In [3]:
cdmx = (
    gpd
    .read_file(os.path.join(PATH_DATA, "localidadurbana", "LocalidadUrbana.shp"))
    .to_crs(CRS)
    .pipe(lambda df: df[df.NOM == "DISTRITO FEDERAL"])
    .h3.polyfill_resample(9)
    [["geometry"]]
    # Filtramos solo aquellos hexágonos en los que haya habido al menos un accidente
    .pipe(lambda df: df.loc[gpd.sjoin(accidents, df, predicate="intersects")["h3_polyfill"].unique()])
    # Este mide 428 metros de largo
)

NameError: name 'accidents' is not defined

In [13]:
# Calculé y cada uno de estos hexágonos mide 1.031km de largo (de la parte más ancha)
# Para el análisis consideraré radios de 500 metros
centroides = (
    cdmx
    .assign(
        latitude=lambda x: x.centroid.y,
        longitude=lambda x: x.centroid.x
    )
    [["latitude", "longitude"]]
)

json_file = os.path.join(PATH_DATA, "raw-data", "businesses-cdmx.json")
radius = 214

for row in centroides.itertuples():
    break
    current_data = append_items_to_file(json_file, {})
    if row.Index in current_data.keys():
        print(f"Skipping {row.Index}", end="\r")
        continue
       
    print(row, end="\r")
    try:
        response = gpa.get_places_count(
            latitude=row.latitude,
            longitude=row.longitude,
            radius_m=radius
        )
        print(response, end="\r")
    except requests.exceptions.HTTPError as e:
        print(e, end="\r")
        time.sleep(1)
        continue
    
    store_data = {
        row.Index: {
            "latitude":row.latitude,
            "longitude":row.longitude,
            "count":response.count,
            "radius":radius
        }
    }
    
    append_items_to_file(
        path=json_file,
        new_data=store_data
    )
    time.sleep(.1)

In [14]:
with open(json_file, "r") as f:
    data = json.loads(f.read())
    negocios = pd.DataFrame(data).transpose()

In [16]:
fig, ax = plt.subplots(figsize=(10, 10))

ax_position = ax.get_position()
cax = fig.add_axes([
    # left, bottom, width, height (x,y) (width, height)
    ax_position.y0 + 0.03,
    ax_position.x0 - 0.07,
    ax_position.width - 0.1,
    0.03
])
cax.set_frame_on(False)
cax.tick_params(axis='x', colors='black')

(
    cdmx
    .join(negocios)
    .assign(log_count=lambda x: x["count"].apply(np.sqrt))
    .plot(
        ax=ax,
        cax=cax,
        column="log_count",
        legend=True,
        cmap='GnBu',
        legend_kwds={"label": "sqrt(n)", "orientation": "horizontal"}    
    )
)

vialidades.plot(
    ax=ax, 
    linewidth=.3, 
    color='gray', 
    alpha=.7
)
ax.set_axis_off()
fig.suptitle("Establecimientos en la CDMX", ha="left", x=0.112, y=.935, color="gray", fontsize=15)
ax.set_title(
    "Total agrupado por área", 
    color='darkgray', loc='left', fontsize=10,
    ha="left", x=0.035, y=.935
)
fig.tight_layout()
if False:
    fig.savefig(
        os.path.join(PATH_DATA, "graphs", "establecimientos-en-la-cdmx.png"),
        dpi=300, 
        transparent=True
    )

plt.close()

In [20]:
# La verdad no veo nada de correlación entre vialidades y número de establecimientos
# Pero ahorita veo qué pedo
hexagons_con_via_primaria = (
    gpd
    .sjoin(left_df=vialidades, right_df=cdmx, predicate="intersects")
    .h3_polyfill
    .unique()
)
pdf = (
    cdmx
    .join(negocios)
    .assign(has_via_primaria=lambda x: x.index.isin(hexagons_con_via_primaria))
)

fig, ax = plt.subplots(figsize=(5,3.5))

def clean_ax(ax):
    ax.spines.top.set_visible(False)
    ax.spines.right.set_visible(False)

    axis_color = "#979dac"
    ax.xaxis.label.set_color(axis_color)
    ax.yaxis.label.set_color(axis_color)
    ax.spines.bottom.set_color(axis_color)
    ax.spines.left.set_color(axis_color)
    ax.tick_params(axis='both', colors=axis_color)
    ax.grid(axis='y', alpha=.2, linestyle=':')
    
    ttl = ax.title
    ttl.set_position([.5, 2])
    
clean_ax(ax)
sns.kdeplot(
    data=pdf,
    x="count",
    hue="has_via_primaria",
    fill=True,
    common_norm=True,
    palette="crest",
    alpha=.5,
    linewidth=0
)
ax.legend(["Con vía primara", "Sin vía primaria"], frameon=False, labelcolor="#979dac", fontsize=7, ncols=1)
ax.set_xlabel("Establecimientos")
fig.suptitle("Total de establecimientos", ha="left", x=0.063, y=.91, color="gray")
ax.set_title("Distribuciones con y sin vías primarias", color='darkgray', loc='left', fontsize=9, ha="left", x=-.135, y=1.1)
ax.set_xlim(left=-50, right=400)
fig.tight_layout()
if False:
    fig.savefig(
        os.path.join(PATH_DATA, "graphs", "distribucion-establecimientos-cdmx-hexagonos.png"),
        dpi=300,
        transparent=True
    )
plt.close()

In [22]:
pdf.groupby("has_via_primaria")["count"].agg(["mean", "std"])

                       mean        std
has_via_primaria
False             56.858759  63.366424
True              77.791406  69.104422

In [24]:
cdmx

                                                          geometry
h3_polyfill
8949958e8c3ffff  POLYGON ((-99.06313 19.34432, -99.06189 19.345...
894995b8153ffff  POLYGON ((-99.15261 19.46617, -99.15137 19.467...
894995ba55bffff  POLYGON ((-99.18154 19.38747, -99.1803 19.3890...
894995ba54bffff  POLYGON ((-99.1811 19.39083, -99.17986 19.3924...
89499584bcfffff  POLYGON ((-99.19118 19.36124, -99.18994 19.362...
...                                                            ...
894995b900bffff  POLYGON ((-99.07257 19.46111, -99.07133 19.462...
894995b939bffff  POLYGON ((-99.07408 19.47319, -99.07284 19.474...
894995b123bffff  POLYGON ((-99.21609 19.40813, -99.21485 19.409...
894995ba1afffff  POLYGON ((-99.19968 19.41492, -99.19844 19.416...
894995b14b7ffff  POLYGON ((-99.2524 19.36766, -99.25116 19.3692...

[5000 rows x 1 columns]

In [23]:
gpa.DEFAULT_BUSINESS_TYPES

['restaurant',
 'cafe',
 'shopping_mall',
 'supermarket',
 'convenience_store',
 'grocery_store',
 'store',
 'gas_station',
 'bank',
 'atm',
 'hospital',
 'pharmacy',
 'school',
 'gym',
 'night_club',
 'transit_station',
 'bus_station',
 'subway_station']