In [1]:
import pandas as pd

In [66]:
volumen = pd.read_clipboard()

In [84]:
indicadores = pd.read_clipboard()

In [85]:
volumen.head()

,indicador,volumen_total_anual,lat,long,1,2,3,4,5,6,7,8,9,10,11,12,year
0,64,7301916,19.363370,-99.267326,8.2,8.2,7.7,8.8,8.8,8.1,7.0,8.6,8.4,9.2,8.8,7.9,2024
1,65,808005,19.335797,-99.311029,7.4,8.8,8.2,9.3,9.6,8.2,6.4,7.9,8.9,9.0,8.9,7.4,2024
2,66-01,16256806,19.332816,-99.314301,7.7,8.0,8.6,8.5,8.7,8.2,8.5,8.4,8.0,8.6,8.5,8.3,2024
3,66-02,794888,19.333648,-99.313782,8.6,7.3,7.5,7.9,8.5,6.9,6.1,7.4,8.3,8.4,10.1,13.0,2024
4,66-03,5509663,19.331739,-99.315122,7.8,7.8,8.4,8.2,8.6,8.5,8.8,8.8,8.2,8.7,8.1,8.1,2024

In [86]:
indicadores.head()

,indicador,carretera,movimiento,caseta,kilometro,year
0,211,México-Puebla,Chalco (Panasonic)-México,Ixtapaluca,31.9,2017
1,212,México-Puebla,Chalco (Panasonic)-México,Ixtapaluca,31.9,2018
2,211,México-Puebla,Chalco (Panasonic)-México,Ixtapaluca,31.9,2019
3,214,México-Puebla,Chalco (Panasonic)-México,Ixtapaluca,31.9,2020
4,212,México-Puebla,Chalco (Panasonic)-México,Ixtapaluca,31.9,2021

In [100]:
(
    volumen
    .merge(
        indicadores,
        on=["indicador", "year"],
        how="inner"
    )
    .pivot(
        index=["carretera", "movimiento", "caseta", "kilometro"],
        columns="year",
        values="indicador"
    )
    # Nos quedamos solo con los radares permanentes que hayan estado durante
    # todo el tiempo que se esté estudiando los datos
    .pipe(lambda df: df[df.isna().astype(int).sum(axis=1) == 0])
    .melt(ignore_index=False, value_name='indicador')
    .reset_index()
)

,carretera,movimiento,caseta,kilometro,year,indicador
0,Constituyentes-La Marquesa,Constituyentes-Contadero,Contadero,23.430,2015,61
1,Constituyentes-La Marquesa,Constituyentes-La Marquesa,La Venta,24.000,2015,062-01
2,Constituyentes-La Marquesa,Constituyentes-La Venta,La Venta,24.000,2015,062-02
3,Constituyentes-La Marquesa,Constituyentes-Santa Fe,Santa Fe,17.626,2015,60
4,Constituyentes-La Marquesa,La Venta-La Marquesa,La Venta,24.000,2015,062-03
...,...,...,...,...,...,...
195,México-Querétaro,Tepeji-Polotitlán,Polotitlán,133.050,2024,211
196,México-Tizayuca,Derivador López Portillo,Revolución,22.800,2024,154-01
197,México-Tizayuca,Indios Verdes-San Cristóbal Ecatepec,San Cristóbal,21.000,2024,153
198,México-Tizayuca,Indios Verdes-Tizayuca,Ojo de Agua,25.000,2024,155
199,México-Tizayuca,México-Lechería,Revolución,22.800,2024,154-02